metric: COCO
num_classes: 80

TrainDataset:
  name: COCODataSet
  image_dir: train
  anno_path: train/annotations.json
  dataset_dir: dataset/coco/lpr
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: COCODataSet
  image_dir: valid
  anno_path: valid/annotations.json
  dataset_dir: dataset/coco/lpr
  allow_empty: true

TestDataset:
  name: ImageFolder
  anno_path: test/annotations.json # also support txt (like VOC's label_list.txt)
  dataset_dir: dataset/coco/lpr # if set, anno_path will be 'dataset_dir/anno_path'
